-- V012: Agrega RENTAL_DELIVER al ENUM de role_permissions.permission
-- El valor RENTAL_DELIVER fue agregado al enum Permission.java pero no estaba en el ENUM de la BD.

ALTER TABLE role_permissions
    MODIFY COLUMN permission ENUM(
        'CALENDAR_SYNC','CALENDAR_VIEW',
        'CATALOG_MANAGE','CATALOG_VIEW',
        'CONTRACT_CREATE','CONTRACT_DELETE','CONTRACT_DOWNLOAD','CONTRACT_EDIT','CONTRACT_SIGN','CONTRACT_VIEW',
        'CUSTOMER_CREATE','CUSTOMER_DELETE','CUSTOMER_EDIT','CUSTOMER_VIEW',
        'PAYMENT_CREATE','PAYMENT_DELETE','PAYMENT_EDIT','PAYMENT_REFUND','PAYMENT_VIEW',
        'RENTAL_CANCEL','RENTAL_COMPLETE','RENTAL_CREATE','RENTAL_DELETE','RENTAL_DELIVER','RENTAL_EDIT','RENTAL_VIEW',
        'REPORT_EXPORT','REPORT_VIEW',
        'SECURITY_ACCESS_LOG','SECURITY_PERMISSIONS','SECURITY_ROLES',
        'SETTINGS_EDIT','SETTINGS_VIEW',
        'USER_CREATE','USER_DELETE','USER_EDIT','USER_ROLES','USER_VIEW',
        'VEHICLE_CREATE','VEHICLE_DELETE','VEHICLE_EDIT','VEHICLE_VIEW'
    ) NOT NULL;
